### PR TITLE
Fixed #22

### LINKED ISSUE #22: Word count option greyed out, keybinding unresponsive
Didn't touch my sublime installation, the plugin just stopped working. Tried reinstalling the package but the problem persists. The word count option is greyed out, and the keyboard shortcut does not work. No error message or anything.

### PR DESCRIPTION
**Pull request by mpvharmelen**

### CODE REVIEW

**Comment by kevinstadler** [comment]
*fingers crossed* @faaizajaz please let us know if it all blows up again!

**Comment by faaizajaz** [comment]
:(

`Reloading plugin C:\Users\Faaiz\AppData\Roaming\Sublime Text 2\Packages\LaTeX Word Count\WordCount.py`
`Traceback (most recent call last):`
  `File ".\sublime_plugin.py", line 62, in reload_plugin`
  `File ".\WordCount.py", line 117, in <module>`
    `r"([^{}]+)\.(tmLanguage|sublime-syntax)".format(re.escape(os.sep))`
`ValueError: zero length field name in format`

**Comment by kevinstadler** [comment]
Aaaand back to before. @mpvharmelen I wonder if the problem also has to do with the `^{}` bit and not just the os.sep character? (I have neither a Windows machine nor ST2 here to test myself...)

**Comment by mpvharmelen** [comment]
Yes, I think it was both. First the backslash character of the Windows separator escaped important regex characters. This second error is probably because of the Python version ([source](http://stackoverflow.com/questions/5446964/valueerror-zero-length-field-name-in-format-error-in-python-3-0-3-1-3-2#5447119)). I'll push a fix in a moment.

**Pull request merged**
